// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubbyApi.DataLayer.MySQL.EFCore.Data;

namespace SubbyApi.DataLayer.MySQL.EFCore.Migrations
{
    [DbContext(typeof(SubbyContext))]
    partial class SubbyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SubbyApi.DataLayer.MySQL.EFCore.DataModels.SiteSettingsDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<bool>("UseLogoOnFilter")
                        .HasColumnName("use_logo_on_filter")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UseLogoOnSubscription")
                        .HasColumnName("use_logo_on_subscription")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
